import {
  amber,
  blue,
  blueGrey,
  brown,
  common,
  cyan,
  deepOrange,
  deepPurple,
  green,
  grey,
  indigo,
  lightBlue,
  lightGreen,
  lime,
  orange,
  pink,
  purple,
  red,
  teal,
  yellow,
} from '@mui/material/colors';

export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  important: '#root',
  theme: {
    screens: {
      xs: { max: '0px' },
      sm: { max: '600px' },
      md: { max: '900px' },
      lg: { max: '1200px' },
      xl: { max: '1536px' },
    },
    extend: { colors: {
      amber,
      black: common.black,
      blue,
      blueGrey,
      brown,
      cyan,
      deepOrange,
      deepPurple,
      green,
      grey,
      indigo,
      lightBlue,
      lightGreen,
      lime,
      orange,
      pink,
      purple,
      red,
      teal,
      white: common.white,
      yellow,
    } },
  },
  corePlugins: { preflight: false },
};
